### ISSUE TITLE
Uncaught Error: Notification must be created with string message: null

### ISSUE THREAD

**Issue by MattHodge** [tomoya/rubocop-auto-correct#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [rubocop-auto-correct](https://github.com/tomoya/rubocop-auto-correct) package, v1.0.0
### Stack Trace

Uncaught Error: Notification must be created with string message: null

```
At C:\Users\<My_user>\AppData\Local\atom\app-1.1.0\resources\app.asar\src\notification.js:25

Error: Notification must be created with string message: null
    at Notification.module.exports.Notification.validate (C:\Users\<My_user>\AppData\Local\atom\app-1.1.0\resources\app.asar\src\notification.js:25:15)
    at new Notification (C:\Users\<My_user>\AppData\Local\atom\app-1.1.0\resources\app.asar\src\notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addError (C:\Users\<My_user>\AppData\Local\atom\app-1.1.0\resources\app.asar\src\notification-manager.js:41:35)
    at file:///C:/Users/<My_user>/.atom/packages/rubocop-auto-correct/lib/rubocop-auto-correct.coffee:95:35
    at C:\Users\<My_user>\.atom\packages\rubocop-auto-correct\node_modules\which\which.js:91:20
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:06.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 rubocop-auto-correct:current-file (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-light-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-aspx, v0.4.0
language-php, v0.32.0
language-powershell, v2.1.0
line-ending-converter, v1.3.2
linter, v1.10.0
linter-rubocop, v0.4.4
linter-ruby, v1.2.0
minimap, v4.16.0
monokai, v0.14.0
pretty-json, v0.4.1
rubocop-auto-correct, v1.0.0

# Dev
No dev packages
```

**Comment by tomoya** [comment]
Thank you for your report. I'm using OSX. But, I have Windows 8 on parallels VM.
So, I will check for Windows 8, When I have a time.

**Comment by MattHodge** [comment]
Thanks @tomoya 

When try _Autocorrect Current File_ this message appears:

![Imgur](http://i.imgur.com/q41QPWk.png)

Perhaps related to the version of ruby in ChefDK?

```
warning: parser/current is loading parser/ruby21, which recognizes warning: 2.1.7-compliant syntax, but you are running 2.1.6. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

```
different prefix: "E:/" and "C:/Users/<My_User>/AppData/Local/atom/app-1.1.0" C:/opscode/chefdk/embedded/lib/ruby/2.1.0/pathname.rb:503:in relative_path_from' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/path_util.rb:14:inrelative_path' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/config.rb:163:in path_relative_to_config' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:248:inblock in file_name_matches_any?' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:243:in each' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:243:inany?' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:243:in file_name_matches_any?' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:205:inrelevant_file?' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/cop.rb:209:in excluded_file?' 
```

```
C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/commissioner.rb:64:inblock in remove_irrelevant_cops' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/commissioner.rb:64:in reject!' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/commissioner.rb:64:inremove_irrelevant_cops' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/commissioner.rb:49:in investigate' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cop/team.rb:34:ininspect_file' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:190:in inspect_file' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:157:inblock in do_inspection_loop' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:151:in loop' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:151:indo_inspection_loop'
C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:93:in process_file' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:58:inblock in inspect_files' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:56:in each' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:56:ininspect_files' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:34:in run' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/lib/rubocop/cli.rb:26:inrun' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/bin/rubocop:13:in block in <top (required)>' C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:294:inrealtime' C:/Users/<My_User>/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.35.0/bin/rubocop:12:in <top (required)>' C:/opscode/chefdk/bin/rubocop:23:inload' C:/opscode/chefdk/bin/rubocop:23:in
```
