### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by andrewkhouzam** [tomoya/rubocop-auto-correct#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: [rubocop-auto-correct](https://github.com/tomoya/rubocop-auto-correct) package 1.5.1

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/rubocop-auto-correct/lib/rubocop-auto-correct.coffee:116:27
    at /packages/rubocop-auto-correct/node_modules/which/which.js:87:20
    at /packages/rubocop-auto-correct/node_modules/isexe/index.js:42:5
    at /packages/rubocop-auto-correct/node_modules/isexe/mode.js:8:5
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -1:27.8.0 core:confirm (input.hidden-input)
     -1:27.8.0 rubocop-auto-correct:current-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:18.4.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:14.3.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:45 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:42.1.0 core:move-down (input.hidden-input)
     -0:41.7.0 core:move-up (input.hidden-input)
     -0:41.5.0 core:confirm (input.hidden-input)
     -0:41.5.0 rubocop-auto-correct:current-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:32 command-palette:toggle (input.hidden-input)
     -0:28.6.0 core:move-down (input.hidden-input)
     -0:28.4.0 core:confirm (input.hidden-input)
     -0:28.4.0 rubocop-auto-correct:current-file (input.hidden-input)
     -0:17.3.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15 core:confirm (input.hidden-input)
     -0:15 rubocop-auto-correct:current-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-ternjs 0.18.2 
auto-detect-indentation 1.3.0 
emmet 2.4.3 
file-icons undefined 
highlight-selected 0.12.0 
minimap 4.26.8 
rails-snippets 2.12.0 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
```

**Comment by tomoya** [comment]
Can I see the example ruby code?

**Comment by alex3o0** [comment]
In my case this issue happened on the application_controller.rb with ruby 2.3 and ruby on rails 5.0

````
# frozen_string_literal: false
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  include ActionController::Serialization
  except = [:new, :create]
  before_action :authenticate_user!, unless: :devise_controller?, except: except
  before_action :configure_permitted_parameters, if: [:devise_controller?]

  rescue_from StandardError do |exception|
    render message_500(exception), status: 500
  end

  def message_500(exception)
    { json: { errors: [I18n.t('errors.status_500')], exception: [exception] } }
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:phone, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end
````

**Comment by tomoya** [comment]
@alex3o0, thanks to your following.
I tried to auto fix your code. But, no error occurred.

Corrected core is below:
```
# frozen_string_literal: false

class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  include ActionController::Serialization
  except = %i[new create]
  before_action :authenticate_user!, unless: :devise_controller?, except: except
  before_action :configure_permitted_parameters, if: [:devise_controller?]

  rescue_from StandardError do |exception|
    render message_500(exception), status: 500
  end

  def message_500(exception)
    { json: { errors: [I18n.t('errors.status_500')], exception: [exception] } }
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[phone password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end
```

I guess this error has occurred by can not parse JSON that was outputted by rubocop. 
So, I recommend updating rubocop if you can do it.

Thanks,

**Comment by andrewkhouzam** [comment]
Thank you!
