### ISSUE TITLE
Uncaught SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by arthurstockler** [tomoya/rubocop-auto-correct#41]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [rubocop-auto-correct](https://github.com/tomoya/rubocop-auto-correct) package 1.5.1

### Stack Trace

Uncaught SyntaxError: Unexpected token  in JSON at position 0

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token  in JSON at position 0
    at Object.parse (native)
    at /packages/rubocop-auto-correct/lib/rubocop-auto-correct.coffee:116:27
    at /packages/rubocop-auto-correct/node_modules/which/which.js:87:20
    at /packages/rubocop-auto-correct/node_modules/isexe/index.js:42:5
    at /packages/rubocop-auto-correct/node_modules/isexe/mode.js:8:5
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:15.3.0 core:move-up (input.hidden-input)
     -0:15.1.0 editor:consolidate-selections (input.hidden-input)
     -0:15.1.0 core:cancel (input.hidden-input)
     -0:14.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:14.6.0 editor:newline (input.hidden-input)
     -0:13.5.0 autocomplete-plus:cancel (input.hidden-input)
     -0:12.8.0 editor:newline (input.hidden-input)
     -0:08.6.0 intentions:highlight (input.hidden-input)
     -0:08.3.0 core:copy (input.hidden-input)
     -0:05.6.0 intentions:highlight (input.hidden-input)
     -0:05.5.0 core:paste (input.hidden-input)
     -0:05.2.0 intentions:highlight (input.hidden-input)
     -0:05.0 core:save (input.hidden-input)
     -0:02.9.0 rubocop-auto-correct:current-file (div.line)
     -0:01.0 intentions:highlight (input.hidden-input)
     -0:00.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-docker 1.1.7 
linter 2.1.2 
linter-rubocop 1.1.1 
linter-ui-default 1.2.2 
rubocop-auto-correct 1.5.1 
```

**Comment by tomoya** [comment]
What is your rubocop version? And, please let me see your ruby code.

**Comment by lanej** [comment]
I got this with 0.42.0

**Comment by ricardograca** [comment]
I got this with rubocop 0.74.0

**Comment by ricardograca** [comment]
If anyone is still trying to use this package (like I was) there's a better alternative that works as expected: https://atom.io/packages/atom-beautify
